import { Link } from "react-router-dom";

import { Button } from "../../components/button";
import { useSession } from "../../app/session-client";
import { useCustomerAddresses, useDeleteCustomerAddress } from "./orders-api";

export function AccountPage() {
	const session = useSession();
	const registered = Boolean(session.data?.user);
	const addresses = useCustomerAddresses(registered);
	const remove = useDeleteCustomerAddress();
	return <section className="space-y-5 pb-4"><header className="rounded-card bg-ink p-6 text-surface shadow-float"><p className="text-xs font-medium uppercase tracking-[0.16em] text-action">Customer account</p><h1 className="mt-2 text-3xl font-medium tracking-tight">{registered ? "Your account" : "Your guest checkout"}</h1><p className="mt-2 max-w-xl text-sm leading-6 text-surface/75">{registered ? "Saved addresses and order history stay with your account." : "Orders are available in this browser session. Sign in to keep your history and saved addresses across devices."}</p></header>
		{registered ? <section className="rounded-card bg-surface p-5 shadow-float"><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="text-xl font-medium tracking-tight">Saved addresses</h2><Link className="text-sm font-medium text-focus underline" to="/checkout">Add at checkout</Link></div>{addresses.isPending ? <p aria-busy="true" className="mt-4 text-sm text-muted">Loading saved addresses…</p> : addresses.isError ? <p className="mt-4 text-sm text-[#8e301d]">We could not load your saved addresses. <button className="underline" onClick={() => void addresses.refetch()} type="button">Retry</button></p> : addresses.data?.length ? <div className="mt-4 grid gap-3">{addresses.data.map((address) => <article className="flex items-start justify-between gap-3 rounded-2xl border border-line p-4" key={address.id}><address className="not-italic text-sm leading-6"><strong>{address.label ?? address.recipientName}</strong><br />{address.addressLine1}{address.addressLine2 ? <><br />{address.addressLine2}</> : null}<br />{address.city}, {address.state} {address.postalCode}</address><Button disabled={remove.isPending} onClick={() => remove.mutate({ id: address.id, version: address.version })} type="button" variant="quiet">Remove</Button></article>)}</div> : <p className="mt-4 text-sm text-muted">Save an address during checkout to make your next order quicker.</p>}{remove.isError ? <p aria-live="polite" className="mt-3 text-sm text-[#8e301d]">We could not remove that address. Please refresh and try again.</p> : null}</section> : <section className="rounded-card bg-surface p-5 shadow-float"><h2 className="text-xl font-medium tracking-tight">Want to save your details?</h2><p className="mt-2 text-sm leading-6 text-muted">Create an account before your next order. Your guest cart can be merged after sign-in.</p><Link className="mt-4 inline-flex min-h-11 items-center rounded-full bg-action px-5 text-sm font-medium text-ink" to="/login">Sign in or create an account</Link></section>}
		<section className="rounded-card bg-surface p-5 shadow-float"><h2 className="text-xl font-medium tracking-tight">Orders</h2><p className="mt-2 text-sm text-muted">Review deliveries, track their status, or reorder available items.</p><Link className="mt-4 inline-flex min-h-11 items-center rounded-full border border-line px-5 text-sm font-medium" to="/orders">View your orders</Link></section></section>;
}
